---
language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
install:
  - pip install molecule docker
before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-pip bobbyrenwick.pip
  - cd bobbyrenwick.pip
script:
  - molecule --version
  - ansible --version
  - molecule test
