---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      # Skip the pipefail rule (306) due to controversy / there-be-dragons
      # https://github.com/ansible/ansible-lint/issues/497
      # https://github.com/ansible/ansible/issues/12903
      x: ["306"]
verifier:
  name: testinfra
  lint:
    name: flake8
